### ISSUE TITLE
Can't parse first line error

### ISSUE THREAD

**Issue by neilio** [automatthias/whatsapp-archive#1]
I don't know if this is still maintained (but I hope so!) - I've tried running this against my _chat.txt export and I get this error. Not sure if it's because the formatting of the date line in my export file is wrong but it would be awesome to get this working.

This is what one line of my chat export looks like:

2016-06-27, 8:04:08 AM: Neil: Hi

Any suggestions?

**Comment by automaciej** [comment]
Hi Neil,

I've submitted a commit that adds support for the example you added. If you see any further errors, feel free to report them!

**Comment by neilio** [comment]
Thanks! Really appreciate it. The change you made worked for me.
