### ISSUE TITLE
Possible to source media?

### ISSUE THREAD

**Issue by neilio** [automatthias/whatsapp-archive#2]
I was wondering if it was possible to add the ability to embed images (and video?) into the output? I'm thinking something super simple - just img src the images, for example.

**Comment by neilio** [comment]
As an example all of my images have a date prefix with a UUID at the end:

2016-06-27-PHOTO-00000050.jpg

**Comment by automaciej** [comment]
Certainly it could be possible to download a whole folder with a WhatsApp export and add HTML tags to display media on the page. So far I've worked with the text-only exports, that can reach a few months back in time. Exports that include media were too short for me, so I didn't have too much interest in them.

From the cursory looking at the export, the syntax is very loose, for example the phrase saying "attached file" is internationalized, so a simple parser won't work.

I agree that this is a good feature, but I at the moment I can't commit to implementing it. If anybody writes a patch, I will be happy to review it and include it in the project.

**Comment by Sogl** [comment]
Any news on this?

**Comment by automaciej** [comment]
No news, I won't work on this now – sorry – but the project is open for contributions.

**Comment by automaciej** [comment]
Pull request #9 implements this, I reviewed the code, it requires some changes, but looks good overall.
