### ISSUE TITLE
how its work?  i am new here please make a web on it or share any video. 

### ISSUE THREAD

**Issue by ashutosh6999** [automatthias/whatsapp-archive#3]
i am new here please make a web on it or share any video how to convert please. its very important for me. help me

**Comment by automaciej** [comment]
To run this, you need to know how to run Python programs in general, and how to install dependencies / libraries. Sorry if this is not very user friendly. I made this tool myself and only shared it here for those who want.

Also, see the README file, it contains a short description with instructions.
